from fastapi import APIRouter, HTTPException
from datetime import datetime, timezone
import uuid
from database import get_db
from models import Podcast, Subscription, Episode
from services import podcast_index, rss

router = APIRouter(prefix="/podcasts", tags=["podcasts"])


@router.get("/search")
async def search_podcasts(q: str, limit: int = 20) -> list[Podcast]:
    """Search podcasts via Podcast Index API."""
    results = await podcast_index.search_podcasts(q, limit)
    return [
        Podcast(
            id=str(r["id"]),
            title=r.get("title", ""),
            author=r.get("author", ""),
            description=r.get("description", ""),
            image_url=r.get("image"),
            feed_url=r.get("url", ""),
            website_url=r.get("link"),
            episode_count=r.get("episodeCount"),
        )
        for r in results
    ]


@router.get("/subscriptions")
async def list_subscriptions() -> list[Subscription]:
    db = await get_db()
    try:
        rows = await db.execute_fetchall("SELECT * FROM subscriptions ORDER BY subscribed_at DESC")
        return [Subscription(**dict(r)) for r in rows]
    finally:
        await db.close()


@router.post("/subscriptions/{podcast_id}")
async def subscribe(podcast_id: str, feed_url: str, title: str, image_url: str = None):
    db = await get_db()
    try:
        await db.execute(
            """INSERT OR IGNORE INTO subscriptions (podcast_id, feed_url, title, image_url, subscribed_at)
               VALUES (?, ?, ?, ?, ?)""",
            (podcast_id, feed_url, title, image_url, datetime.now(timezone.utc).isoformat()),
        )
        await db.commit()
    finally:
        await db.close()
    return {"status": "subscribed"}


@router.delete("/subscriptions/{podcast_id}")
async def unsubscribe(podcast_id: str):
    db = await get_db()
    try:
        await db.execute("DELETE FROM subscriptions WHERE podcast_id = ?", (podcast_id,))
        await db.commit()
    finally:
        await db.close()
    return {"status": "unsubscribed"}


@router.get("/suggestions")
async def get_suggestions() -> list[dict]:
    """Return non-dismissed podcast suggestions generated by the daily job."""
    db = await get_db()
    try:
        rows = await db.execute_fetchall(
            "SELECT * FROM suggestions WHERE dismissed = 0 ORDER BY suggested_at DESC"
        )
        return [dict(r) for r in rows]
    finally:
        await db.close()


@router.post("/suggestions/{suggestion_id}/dismiss")
async def dismiss_suggestion(suggestion_id: str):
    db = await get_db()
    try:
        await db.execute("UPDATE suggestions SET dismissed = 1 WHERE id = ?", (suggestion_id,))
        await db.commit()
    finally:
        await db.close()
    return {"status": "dismissed"}


@router.get("/feed")
async def get_feed() -> list[dict]:
    """Single-query combined feed: episodes joined with subscriptions + distill counts."""
    db = await get_db()
    try:
        rows = await db.execute_fetchall(
            """
            SELECT
                e.id, e.podcast_id, e.title, e.description, e.audio_url, e.duration_seconds,
                e.published_at, e.image_url, e.downloaded, e.transcript_status, e.ads_detected,
                s.title  AS podcast_title,
                s.image_url AS podcast_image,
                COUNT(g.id) AS distill_count
            FROM episodes e
            JOIN subscriptions s ON e.podcast_id = s.podcast_id
            LEFT JOIN gists g ON g.episode_id = e.id
            GROUP BY e.id
            ORDER BY e.published_at DESC
            LIMIT 50
            """
        )
        return [dict(r) for r in rows]
    finally:
        await db.close()


@router.get("/{podcast_id}/episodes")
async def get_episodes(podcast_id: str, refresh: bool = False, limit: int = 100, offset: int = 0) -> list[Episode]:
    db = await get_db()
    try:
        if refresh:
            row = await db.execute_fetchone(
                "SELECT feed_url FROM subscriptions WHERE podcast_id = ?", (podcast_id,)
            )
            if not row:
                raise HTTPException(404, "Podcast not subscribed")
            episodes = await rss.fetch_episodes(row["feed_url"], podcast_id)
            for ep in episodes:
                await db.execute(
                    """INSERT OR IGNORE INTO episodes
                       (id, podcast_id, title, description, audio_url, duration_seconds, published_at, image_url)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                    (ep.id, ep.podcast_id, ep.title, ep.description, ep.audio_url,
                     ep.duration_seconds, ep.published_at.isoformat() if ep.published_at else None, ep.image_url),
                )
            await db.commit()

        # Bug 8: Paginate — cap at 500, default 100
        limit = min(max(limit, 1), 500)
        offset = max(offset, 0)
        rows = await db.execute_fetchall(
            "SELECT * FROM episodes WHERE podcast_id = ? ORDER BY published_at DESC LIMIT ? OFFSET ?",
            (podcast_id, limit, offset),
        )
        return [Episode(**dict(r)) for r in rows]
    finally:
        await db.close()
